### ISSUE TITLE
Importing the API

### ISSUE THREAD

**Issue by theunreal** [Babacooll/lol-api#1]
I'm using xampp on Windows and It's pretty mess to use composer to import the API. I've been trying to look for autoload.php file but I couldn't find, so it will be great if you can create some documentation about installing/importing/using the API on a new web page.

**Comment by Babacooll** [comment]
Hello, I'll add a section to the README as soon as possible about that.

Thanks for feedback !

**Comment by Babacooll** [comment]
After reflection about this issue I don't think the creation of a custom autoloader for composer non-users is a good idea. 

You should use composer as it is the best way to use this library. Why is it a mess to use Composer on  Windows ?

**Comment by nicka206** [comment]
Composer works fine on windows you need to install it directly in your project folder or set up global  variables for it. However it runs from command line and on wi dows it's pretty ugly. I would suggest taking a look at laragon. I just moved over to it at work as our php framework. It uses laravel which has a bit of a learning curve but you'll be better off in the long run. This will give you composer auto set up on windows. A great terminal to use.  Redis. And memcache right out the box.  @theunreal

**Comment by Babacooll** [comment]
@theunreal I close this issue.
