### ISSUE TITLE
New Riot API updates

### ISSUE THREAD

**Issue by SeaRoth** [Babacooll/lol-api#12]
Will you be updating to SummonerV3, matchlistV3 etc?

![image](https://cloud.githubusercontent.com/assets/3461713/25813028/029cdbaa-33cd-11e7-997b-0d5e92f307c5.png)

**Comment by Babacooll** [comment]
Hey it should be handled when I'll check and release the pr #11

**Comment by SeaRoth** [comment]
My bad I should have clicked on pull requests

**Comment by Babacooll** [comment]
Has been fixed
