### ISSUE TITLE
Error [I tried to open]

### ISSUE THREAD

**Issue by marcuxyz** [Babacooll/lol-api#9]
I tried to open the API and an error occurred:

Fatal error: Uncaught Error: Class 'LoLApi\ApiClient' not found in /Applications/XAMPP/xamppfiles/htdocs/leagues/leagues.php:4 Stack trace: #0 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/leagues/leagues.php on line 4

**Comment by ahmedsafadii** [comment]
<img width="403" alt="screen shot 2016-07-17 at 9 56 21 pm" src="https://cloud.githubusercontent.com/assets/6974081/16902510/60b58bc0-4c69-11e6-9a95-b1d43bd0112a.png">
put this above

use LoLApi\ApiClient;

**Comment by Babacooll** [comment]
@MarcusMann Can you confirm this fixes your issue ? (If not did you properly include the composer autoload?)

**Comment by Babacooll** [comment]
Guess this is fixed, thanks @ahmedsafadii
